### ISSUE TITLE
Feedback for milestone 2

### ISSUE THREAD

**Issue by lmguzman** [UBC-MDS/prepackPy#27]
Excellent job! This package was well done and easy to use. The documentation and the examples for usage allowed me to use all the functions with no problem. 

Your tests did the job that was needed when I inputted other things. 

Two minor comments I had were:
- You should add in your example usage that you need to import numpy to get your example arrays.

- Does python treat nan and na the same way? If I use `"NA"` instead of `np.nan` na_counter gives me an error.

**Comment by apchiodo** [comment]
1. You should add in your example usage that you need to import numpy to get your example arrays.
- check.
2. Does python treat nan and na the same way? If I use "NA" instead of np.nan na_counter gives me an error.
- "NA" is not a missing value type in python, it is a string.  We could add a character method to the function in the next iteration of the package, but originally the scope of the function was to identify "true" missing values.
